const queryKeys = {
  GET_RESOURCE_CATEGORY: "GET_RESOURCE_CATEGORY",
  GET_SAVED_RESOURCE_CATEGORY: "GET_SAVED_RESOURCE_CATEGORY",
  GET_SAVED_USER_COUPON: "GET_SAVED_USER_COUPON",
  GET_CHECKED_COUPON: "GET_CHECKED_COUPON",
};

export default queryKeys;
