const queryKeys = {
  GET_USER_PROFILE: "GET_USER_PROFILE",
  GET_OPERATOR_TIMETABLE: "GET_OPERATOR_TIMETABLE",
  GET_USER_REFERRED: "GET_USER_REFERRED",
  GET_USER_BANK: "GET_USER_BANK",
  GET_SPORT_FORECAST: "GET_SPORT_FORECAST",
  GET_All_SPORT_FORECAST: "GET_All_SPORT_FORECAST",
  GET_INSTANT_GAME:"GET_INSTANT_GAME"
};

export default queryKeys;
