const queryKeys = {
  GET_USER_PROFILE: "GET_USER_PROFILE",
  GET_OPERATOR_TIMETABLE: "GET_OPERATOR_TIMETABLE",
  GET_USER_REFERRED: "GET_USER_REFERRED",
  GET_USER_BANK: "GET_USER_BANK",
};

export default queryKeys;
